version: "3.9"
services:
  web:
    build: .
    depends_on:
      - "postgres"
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=olle
  postgres:
    image: "postgres:latest"
    ports:
      - "3500:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=olle
volumes:
  postgres-data:
